spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysite?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qlsjtm12
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug